"""Where recordings live.

Two backends behind one interface:

* **local** - a directory on disk. What the container deployment uses.
* **s3** - any S3-compatible bucket (AWS S3, Cloudflare R2, MinIO, Backblaze).
  The browser uploads straight to the bucket with a presigned PUT and plays
  back from a presigned GET, so audio bytes never pass through the application
  at all. That is what makes this work on a serverless host, where request
  bodies are capped at a few megabytes and the filesystem is read-only.
"""

from __future__ import annotations

import mimetypes
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Protocol, runtime_checkable

from app.config import Settings, get_settings


class StorageError(RuntimeError):
    """Raised when a recording cannot be stored or handed back."""


@dataclass
class UploadTicket:
    """Everything the browser needs to put a file into storage itself."""

    key: str
    #: Where to send the bytes. None when the backend cannot accept a direct
    #: upload, in which case the browser posts to the application instead.
    upload_url: str | None
    method: str = "PUT"
    headers: dict[str, str] | None = None
    expires_in: int = 3600

    @property
    def direct(self) -> bool:
        return self.upload_url is not None


@runtime_checkable
class Storage(Protocol):
    name: str
    #: True when the browser can upload without the request passing through us.
    supports_direct_upload: bool

    def upload_ticket(self, key: str, content_type: str) -> UploadTicket: ...

    def put(self, key: str, stream: BinaryIO, content_type: str) -> int: ...

    def exists(self, key: str) -> bool: ...

    def size(self, key: str) -> int: ...

    def delete(self, key: str) -> None: ...

    def playback_url(self, key: str, expires_in: int = 3600) -> str | None:
        """A URL the browser (or a transcription service) can read directly."""
        ...

    def local_path(self, key: str) -> Path | None:
        """A path on this machine, when there is one. None for remote storage."""
        ...


# --------------------------------------------------------------------------
# Local disk
# --------------------------------------------------------------------------

class LocalStorage:
    name = "local"
    supports_direct_upload = False

    def __init__(self, root: Path):
        self.root = Path(root)

    def _path(self, key: str) -> Path:
        # Keys are generated by the application, never taken from a request,
        # but resolve anyway so a bad one cannot escape the root.
        path = (self.root / key).resolve()
        root = self.root.resolve()
        if not path.is_relative_to(root):
            raise StorageError(f"Refusing to touch {key!r}: outside the storage root.")
        return path

    def upload_ticket(self, key: str, content_type: str) -> UploadTicket:
        return UploadTicket(key=key, upload_url=None)

    def put(self, key: str, stream: BinaryIO, content_type: str) -> int:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("wb") as handle:
            shutil.copyfileobj(stream, handle)
        return path.stat().st_size

    def exists(self, key: str) -> bool:
        return self._path(key).exists()

    def size(self, key: str) -> int:
        return self._path(key).stat().st_size

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)

    def playback_url(self, key: str, expires_in: int = 3600) -> str | None:
        return None  # served by the application itself

    def local_path(self, key: str) -> Path | None:
        if not key:
            return None
        path = self._path(key)
        return path if path.is_file() else None


# --------------------------------------------------------------------------
# S3-compatible object storage
# --------------------------------------------------------------------------

class S3Storage:
    """Presigned direct upload and playback against any S3-compatible bucket."""

    name = "s3"
    supports_direct_upload = True

    def __init__(
        self,
        bucket: str,
        region: str = "auto",
        endpoint_url: str = "",
        access_key_id: str = "",
        secret_access_key: str = "",
        public_base_url: str = "",
    ):
        if not bucket:
            raise StorageError("STORAGE_BUCKET is required when STORAGE_BACKEND=s3.")
        self.bucket = bucket
        self.public_base_url = public_base_url.rstrip("/")
        try:
            import boto3
            from botocore.config import Config
        except ImportError as exc:  # pragma: no cover - depends on optional extra
            raise StorageError(
                "boto3 is not installed. Run `pip install -r requirements.txt`."
            ) from exc

        self._client = boto3.client(
            "s3",
            region_name=region or "auto",
            endpoint_url=endpoint_url or None,
            aws_access_key_id=access_key_id or None,
            aws_secret_access_key=secret_access_key or None,
            # SigV4 presigned URLs are what R2 and modern S3 both expect.
            config=Config(signature_version="s3v4", retries={"max_attempts": 3}),
        )

    def upload_ticket(self, key: str, content_type: str) -> UploadTicket:
        url = self._client.generate_presigned_url(
            "put_object",
            Params={"Bucket": self.bucket, "Key": key, "ContentType": content_type},
            ExpiresIn=3600,
        )
        return UploadTicket(
            key=key,
            upload_url=url,
            method="PUT",
            # The signature covers Content-Type, so the browser must send exactly this.
            headers={"Content-Type": content_type},
            expires_in=3600,
        )

    def put(self, key: str, stream: BinaryIO, content_type: str) -> int:
        self._client.upload_fileobj(
            stream, self.bucket, key, ExtraArgs={"ContentType": content_type}
        )
        return self.size(key)

    def exists(self, key: str) -> bool:
        try:
            self._client.head_object(Bucket=self.bucket, Key=key)
            return True
        except Exception:
            return False

    def size(self, key: str) -> int:
        try:
            return int(self._client.head_object(Bucket=self.bucket, Key=key)["ContentLength"])
        except Exception as exc:
            raise StorageError(f"Recording {key!r} is not in the bucket: {exc}") from exc

    def delete(self, key: str) -> None:
        try:
            self._client.delete_object(Bucket=self.bucket, Key=key)
        except Exception as exc:  # pragma: no cover - network dependent
            raise StorageError(f"Could not delete {key!r}: {exc}") from exc

    def playback_url(self, key: str, expires_in: int = 3600) -> str | None:
        if self.public_base_url:
            return f"{self.public_base_url.rstrip('/')}/{key.lstrip('/')}"
        return self._client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self.bucket, "Key": key},
            ExpiresIn=expires_in,
        )

    def local_path(self, key: str) -> Path | None:
        return None


# --------------------------------------------------------------------------

def get_storage(settings: Settings | None = None) -> Storage:
    settings = settings or get_settings()
    backend = settings.storage_backend.lower()
    if backend == "local":
        return LocalStorage(settings.audio_dir)
    if backend in ("s3", "r2", "minio"):
        return S3Storage(
            bucket=settings.storage_bucket,
            region=settings.storage_region,
            endpoint_url=settings.storage_endpoint_url,
            access_key_id=settings.storage_access_key_id,
            secret_access_key=settings.storage_secret_access_key,
            public_base_url=settings.storage_public_base_url,
        )
    raise StorageError(f"Unknown STORAGE_BACKEND {settings.storage_backend!r}. Use 'local' or 's3'.")


def guess_content_type(filename: str) -> str:
    return mimetypes.guess_type(filename)[0] or "application/octet-stream"
